[local_host]
localhost ansible_port=22 ansible_user=username ansible_password=password ansible_host=127.0.0.1


[local_host:vars]
ssh_key_filename="ansible_rsa"
remote_machine_username="root"
remote_machine_password="abcd"


[ansible_setup_passwordless_setup_group]
rhel-green ansible_port=22 ansible_user=root ansible_host=5.196.214.1/24
rhel-red   ansible_port=22 ansible_user=root ansible_host=5.196.215.1/24[[

[adminservers]
5.196.214.1
[managedservers]
5.196.215.1
